mod recoverable_errors_with_result;

fn main() {
    recoverable_errors_with_result::entry();
}
